package com.aipanelist.model;

import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * Entity representing an analysis report generated by an individual AI agent.
 * Contains the agent's findings, strengths, weaknesses, and recommendations.
 */
@Entity
@Table(name = "analysis_reports")
public class AnalysisReport {
    
    @Id
    @Column(name = "report_id", nullable = false, length = 100)
    private String reportId;
    
    @Column(name = "document_id", nullable = false, length = 100)
    private String documentId;
    
    @Column(name = "agent_id", nullable = false, length = 100)
    private String agentId;
    
    @Enumerated(EnumType.STRING)
    @Column(name = "agent_type", nullable = false, length = 30)
    private AgentType agentType;
    
    @Lob
    @Basic(fetch = FetchType.EAGER)
    @Column(name = "key_findings", nullable = false, columnDefinition = "TEXT")
    private String keyFindings;
    
    @Lob
    @Basic(fetch = FetchType.EAGER)
    @Column(name = "strengths", nullable = false, columnDefinition = "TEXT")
    private String strengths;
    
    @Lob
    @Basic(fetch = FetchType.EAGER)
    @Column(name = "weaknesses", nullable = false, columnDefinition = "TEXT")
    private String weaknesses;
    
    @Lob
    @Basic(fetch = FetchType.EAGER)
    @Column(name = "recommendations", nullable = false, columnDefinition = "TEXT")
    private String recommendations;
    
    @Column(name = "completed_at", nullable = false)
    private LocalDateTime completedAt;
    
    @Column(name = "chunks_analyzed", nullable = false)
    private int chunksAnalyzed;
    
    @Column(name = "chunks_failed", nullable = false)
    private int chunksFailed;
    
    public AnalysisReport() {
    }
    
    public AnalysisReport(String reportId, String documentId, String agentId, AgentType agentType,
                         String keyFindings, String strengths, String weaknesses, String recommendations,
                         LocalDateTime completedAt, int chunksAnalyzed, int chunksFailed) {
        this.reportId = reportId;
        this.documentId = documentId;
        this.agentId = agentId;
        this.agentType = agentType;
        this.keyFindings = keyFindings;
        this.strengths = strengths;
        this.weaknesses = weaknesses;
        this.recommendations = recommendations;
        this.completedAt = completedAt;
        this.chunksAnalyzed = chunksAnalyzed;
        this.chunksFailed = chunksFailed;
    }
    
    public String getReportId() {
        return reportId;
    }
    
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }
    
    public String getDocumentId() {
        return documentId;
    }
    
    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }
    
    public String getAgentId() {
        return agentId;
    }
    
    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }
    
    public AgentType getAgentType() {
        return agentType;
    }
    
    public void setAgentType(AgentType agentType) {
        this.agentType = agentType;
    }
    
    public String getKeyFindings() {
        return keyFindings;
    }
    
    public void setKeyFindings(String keyFindings) {
        this.keyFindings = keyFindings;
    }
    
    public String getStrengths() {
        return strengths;
    }
    
    public void setStrengths(String strengths) {
        this.strengths = strengths;
    }
    
    public String getWeaknesses() {
        return weaknesses;
    }
    
    public void setWeaknesses(String weaknesses) {
        this.weaknesses = weaknesses;
    }
    
    public String getRecommendations() {
        return recommendations;
    }
    
    public void setRecommendations(String recommendations) {
        this.recommendations = recommendations;
    }
    
    public LocalDateTime getCompletedAt() {
        return completedAt;
    }
    
    public void setCompletedAt(LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }
    
    public int getChunksAnalyzed() {
        return chunksAnalyzed;
    }
    
    public void setChunksAnalyzed(int chunksAnalyzed) {
        this.chunksAnalyzed = chunksAnalyzed;
    }
    
    public int getChunksFailed() {
        return chunksFailed;
    }
    
    public void setChunksFailed(int chunksFailed) {
        this.chunksFailed = chunksFailed;
    }
}
